PL/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class AlumnoController : Controller
    {
        // GET: Alumno
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult GetAll()
        {
            //  ML.Departamento departamento = new ML.Departamento();
            ML.Alumno alumno = new ML.Alumno();
            ServiceReferenceAlumno.AlumnoClient servicioAlumno = new ServiceReferenceAlumno.AlumnoClient();
            var result = servicioAlumno.GetAll();
            if (result.Correct)
            {
                alumno.Alumnos = result.Objects.ToList();
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al hacer la consulta de alumnos" + result.ErrorMessage;
            }
            return View(alumno);

        }

        //[HttpGet]
        //public ActionResult Delete(ML.Departamento departamento)
        //{


        //    if (departamento.IdDepartamento > 0)
        //    {
        //        BL.Departamento.DeleteEF(departamento);



        //        return View("Modal");
        //        //return View();
        //        //return RedirectToAction("Usuario");

        //    }
        //    else
        //    {

        //        return View();
        //    }


        //    // return View(IdUsuario);


        //}

        [HttpGet]
        public ActionResult Delete(ML.Alumno alumno)
        {


            if (alumno.IdAlumno > 0)
            {
                //BL.Departamento.DeleteEF(departamento);
                ServiceReferenceAlumno.AlumnoClient servicioAlumno = new ServiceReferenceAlumno.AlumnoClient();

                var result = servicioAlumno.Delete(alumno);


                return View("Modal");
                //return View();
                //return RedirectToAction("Usuario");

            }
            else
            {

                return View();
            }


            // return View(IdUsuario);


        }


        //[HttpPost]
        //public ActionResult Form(ML.Departamento departamento)
        //{
        //    ML.Result result = new ML.Result();

        //    //add o update
        //    if (departamento.IdDepartamento == 0)
        //    {
        //        //add
        //        result = BL.Departamento.AddEF(departamento);
        //        if (result.Correct)
        //        {
        //            ViewBag.Message = "Se inserto correctamente el Departamento";
        //        }
        //        else
        //        {
        //            ViewBag.Message = "Ocurrio un error al insertar el Departamento" + result.ErrorMessage;
        //        }
        //        //return View("/Views/Home/index.cshtml", usuario);


        //    }
        //    else
        //    {
        //        result = BL.Departamento.UpdateEF(departamento);
        //        if (result.Correct)
        //        {
        //            ViewBag.Message = "Se Actualizo correctamente el Departamento";
        //        }
        //        else
        //        {
        //            ViewBag.Message = "Ocurrio un error al actualizo el Departamento" + result.ErrorMessage;
        //        }
        //        //update


        //    }
        //    return View("Modal");

        //}
        [HttpPost]
        public ActionResult Form(ML.Alumno alumno)
        {
            //ML.Result result = new ML.Result();

            //add o update
            if (alumno.IdAlumno == 0)
            {
                //add
                ServiceReferenceAlumno.AlumnoClient servicioDepartamento = new ServiceReferenceAlumno.AlumnoClient();

                var result = servicioDepartamento.Add(alumno);
                if (result.Correct)
                {
                    ViewBag.Message = "Se inserto correctamente el Alumno";
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al insertar el Alumno" + result.ErrorMessage;
                }
                //return View("/Views/Home/index.cshtml", usuario);


            }
            else
            {
                ServiceReferenceAlumno.AlumnoClient servicioDepartamento = new ServiceReferenceAlumno.AlumnoClient();

                var result = servicioDepartamento.Update(alumno);
                if (result.Correct)
                {
                    ViewBag.Message = "Se Actualizo correctamente el Alumno";
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al actualizo el Alumno" + result.ErrorMessage;
                }
                //update


            }
            return View("Modal");

        }


        //[HttpGet]
        //public ActionResult Form(int? idDepartamento)
        //{
        //    ML.Result resultAre = BL.Area.GetAll();
        //    ML.Departamento departamento = new ML.Departamento();
        //    departamento.Area = new ML.Area();

        //    if (resultAre.Correct)
        //    {
        //        departamento.Area.Areas = resultAre.Objects;
        //    }




        //    if (idDepartamento == null)
        //    {
        //        return View(departamento);

        //    }
        //    else
        //    {


        //        ML.Result result = BL.Departamento.GetByIdEF(idDepartamento.Value);


        //        if (result.Correct)
        //        {
        //            departamento = (ML.Departamento)result.Object;
        //            departamento.Area.Areas = resultAre.Objects;
        //            return View(departamento);

        //        }
        //        else
        //        {
        //            ViewBag.Message = "Ocurrio un error al hacer la consulta de Departamento " + result.ErrorMessage;
        //            return View("Modal");
        //        }




        //    }
        //}


        [HttpGet]
        public ActionResult Form(int? idAlumno)
        {


            ML.Alumno alumno = new ML.Alumno();
            //departamento.Area = new ML.Area();

            //if (resultAre.Correct)
            //{
            //    departamento.Area.Areas = resultAre.Objects;
            //}
            if (idAlumno == null)
            {
                return View(alumno);//puede ir vacio

            }
            else
            {

                ServiceReferenceAlumno.AlumnoClient servicioDepartamento = new ServiceReferenceAlumno.AlumnoClient();

                var result = servicioDepartamento.GetById(idAlumno.Value);
                //ML.Result result = BL.Departamento.GetByIdEF(idDepartamento.Value);


                if (result.Correct)
                {
                    alumno = (ML.Alumno)result.Object;
                    //departamento.Area.Areas = resultAre.Objects;
                    return View(alumno);

                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al hacer la consulta de Departamento " + result.ErrorMessage;
                    return View("Modal");
                }
            }
        }

    }
}

PL/Views/Alumno/Form.cshtml
@model ML.Alumno
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="text-center">Formulario de Alumno</h1>
<p>
    En este modulo puedes Agregar en el formulario de Alumno<br />
</p>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Alumno</h2>
        </div>
    </div>

    @using (Html.BeginForm("Form", "Alumno", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.IdAlumno, new { @class = "visually-hidden" })

                    @Html.TextBoxFor(model => model.IdAlumno, new { @class = "visually-hidden form-control" })
                    @Html.ValidationMessageFor(model => model.IdAlumno)
                </div>
            </div>
            <div class="row">

                <div class="col-md-4">
                    @Html.LabelFor(model => model.Nombre)
                    <div class="input-group">
                        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user-plus fa-fade" style="color:#b257a2"></i></span>
                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre", @onkeypress = "SoloLetras(event, 'lblNombre', 'txtNombre')" })
                        @Html.ValidationMessageFor(model => model.Nombre)

                    </div>
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.ApellidoPaterno)
                    <div class="input-group">
                        <span class="input-group-text" id="basic-addon1"><i class="bi bi-calendar2-minus-fill " style="color:#2c4ee7"></i></span>
                        @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control", @id = "txtFechaCreacion", @onkeypress = "SoloLetras(event, 'lblApellidoPaterno', 'txtApellidoPaterno')" })
                        @Html.ValidationMessageFor(model => model.ApellidoPaterno)

                    </div>
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.ApellidoMaterno)
                    <div class="input-group">
                        <span class="input-group-text" id="basic-addon1"><i class="bi bi-calendar2-plus-fill " style="color:#e72c59"></i></span>
                        @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control", @id = "txtFechaModificacion", @onkeypress = "SoloLetras(event, 'lblApellidoMaterno', 'txtApellidoMaterno')" })
                        @Html.ValidationMessageFor(model => model.ApellidoMaterno)

                    </div>
                </div>

              

            </div>


            <div class="form-group">
                <div class="col-md-3">
                    <input type="submit" value="Guardar" class="btn btn-success" />
                    @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    }
</div>

PL/Views/Alumno/GetAll.cshtml
@model ML.Alumno
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <section>

        <h1 class="text-center">Lista de Alumnos</h1>
        <p>
            En este modulo puedes visualizar a las aseguradoras existentes,<br />
            agregar, modificar y eliminarla aseguradora
        </p>
    </section>
    <section>

        <div style="float:right;">
            <div class="row">
                @Html.ActionLink("Agregar", "Form", "Alumno", htmlAttributes: new { @class = "btn btn-success bi bi-person-plus-fill" })
            </div>
        </div>
    </section>
    <hr />
    <section>
        @if (Model.Alumnos == null)
        {
            <div class="row">
                <div class="alert alert-danger" role="alert">
                    @ViewBag.Message
                </div>
            </div>
        }
        else
        {
            <table class="table table-dark table-hover table-bordered table-responsive">
                <thead>
                    <tr>
                        <td class="text-center" style=" font-weight:bold;">Editar</td>
                        <td class="visually-hidden">IdAseguradora</td>
                        <td class="text-center" style="font-weight:bold;">Nombre</td>
                        <td class="text-center" style="font-weight:bold;">ApellidoPaterno</td>
                        <td class="text-center" style="font-weight:bold;">ApellidoMaterno</td>
                        @*<td class="text-center" style="font-weight:bold;">IdUsuario</td>*@
                        @*<td class="text-center" style="font-weight:bold;">Nombre</td>*@
                        <td class="text-center" style=" font-weight:bold;">Eliminar</td>
                    </tr>
                </thead>
                <tbody>

                    @foreach (ML.Alumno aseguradora in Model.Alumnos)
                    {
                        <tr>
                            <td class="text-center"><a class="btn  btn-primary glyphicon glyphicon-edit" href="@Url.Action("Form", "Alumno", new { IdAlumno = aseguradora.IdAlumno })"></a></td>
                            <td class="visually-hidden">@aseguradora.IdAlumno</td>
                            <td>@aseguradora.Nombre </td>
                            <td>@aseguradora.ApellidoPaterno </td>
                            <td>@aseguradora.ApellidoMaterno </td>
                            @* <td class="visually-hidden">@aseguradora.Usuario.IdUsuario</td>*@
                            @*<td class="text-center">@aseguradora.Usuario.Nombre</td>*@
                            <td class="text-center"><a class="btn btn-danger bi bi-trash" href="@Url.Action("Delete", "Alumno", new { IdAlumno = aseguradora.IdAlumno})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                        </tr>
                    }
                </tbody>
            </table>

        }



    </section>
</div>

PL/Views/Alumno/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>