PL/Controllers/AlumnoMateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class AlumnoMateriaController : Controller
    {
        // GET: AlumnoMateria
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Alumno alumno = new ML.Alumno();
            ML.Result result = BL.Alumno.GetAll();

            alumno.Alumnos = result.Objects;

            return View(alumno);
        }
        [HttpGet]
        public ActionResult GetMateriaAsignada(int IdAlumno)
        {
            ML.Result result = BL.AlumnoMateria.GetMateriaAsignada(IdAlumno);
            ML.AlumnoMateria alumnomateria = new ML.AlumnoMateria();

            ML.Result resultalumno = BL.Alumno.GetById(IdAlumno);

            alumnomateria.AlumnosMaterias = result.Objects;
            alumnomateria.Alumno = ((ML.Alumno)resultalumno.Object);

            return View(alumnomateria);
        }
        public ActionResult Delete(int IdAlumnoMateria, int IdAlumno)
        {
            ML.AlumnoMateria alumnomateria = new ML.AlumnoMateria();
            alumnomateria.IdAlumnoMateria = IdAlumnoMateria;
            ML.Result result = BL.AlumnoMateria.Delete(alumnomateria);

            ViewBag.MateriasAsignadas = true;
            ViewBag.IdAlumno = IdAlumno;

            if (result.Correct)
            {
                ViewBag.message = "Se ha eliminado exitosamente el registro";
            }
            else
            {
                ViewBag.message = "ocurrió un error al eliminar el registro " + result.ErrorMessage;

            }
            return PartialView("Modal");
        }
        [HttpGet]
        public ActionResult GetMateriaSinAsignar(int IdAlumno)
        {
            ML.Result result = BL.AlumnoMateria.GetMateriaSinAsignar(IdAlumno);
            ML.AlumnoMateria alumnomateria = new ML.AlumnoMateria();

            ML.Result resultalumno = BL.Alumno.GetById(IdAlumno);

            alumnomateria.AlumnosMaterias = result.Objects;
            alumnomateria.Alumno = ((ML.Alumno)resultalumno.Object);

            return View(alumnomateria);
        }
        [HttpPost]
        public ActionResult GetMateriaSinAsignar(ML.AlumnoMateria alumnomateria)
        {
            ML.Result result = new ML.Result();
            if (alumnomateria.AlumnosMaterias != null)
            {
                foreach (string IdMateria in alumnomateria.AlumnosMaterias)
                {
                    ML.AlumnoMateria alumnomateriaItem = new ML.AlumnoMateria();

                    alumnomateriaItem.Alumno = new ML.Alumno();
                    alumnomateriaItem.Alumno.IdAlumno = alumnomateria.Alumno.IdAlumno;

                    alumnomateriaItem.Materia = new ML.Materia();
                    alumnomateriaItem.Materia.IdMateria = int.Parse(IdMateria);

                    ML.Result resul = BL.AlumnoMateria.Add(alumnomateriaItem);
                }
                result.Correct = true;
                ViewBag.Message = "Se ha actualizado al alumno";
                ViewBag.MateriasAsignadas = true;
                ViewBag.IdAlumno = alumnomateria.Alumno.IdAlumno;
            }
            else
            {
                result.Correct = false;
            }
            return PartialView("Modal");
        }
    }
}

PL/Views/AlumnoMateria/GetAll.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <div class="row">
        <div class="=col-md-12">
            <h2>Alumnos</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
        </div>
    </div>
    <div class="row">
        <br> <br />
    </div>
    <div class="row">
        <div class="col-lg-12">
            <table class="table table-bordered table-responsive">
                <thead class="thead-dark">
                    <tr>
                        <td>Seleccionar</td>
                        <td class="hidden">IdAlumno</td>
                        <td>Nombre</td>


                    </tr>
                </thead>
                <tbody>
                    @foreach (ML.Alumno alumno in Model.Alumnos)
                    {
                        <tr>
                            <td><a class="btn  btn-info glyphicon glyphicon-edit" href="@Url.Action("GetMateriaAsignada", "AlumnoMateria", new { IdAlumno = alumno.IdAlumno })"></a></td>
                            <td class="hidden">@alumno.IdAlumno</td>
                            <td>@alumno.Nombre @alumno.ApellidoPaterno @alumno.ApellidoMaterno </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

PL/Views/AlumnoMateria/GetMateriaAsignada.cshtml
@model ML.AlumnoMateria
@{
    ViewBag.Title = "GetMateriaAsignada";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">

        <h2>Materias Asiganadas a:  @Model.Alumno.Nombre  @Model.Alumno.ApellidoPaterno @Model.Alumno.ApellidoMaterno </h2 >
</div>
</div>

<br />
<div class="form-group">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-success glyphicon glyphicon-plus " href="@Url.Action("GetMateriaSinAsignar", "AlumnoMateria", Model.Alumno)"></a>
        </div>
    </div>
</div>
<div class="row" style="padding-top:30px">
    <div class="col-md-12">
        <table class="table table-bordered">
            <tr>
                <th class="text-center">
                    Selecciona
                </th>
                <th class="text-center hidden" scope="col">
                    IdAlumnoMateria
                </th>
                <th class="text-center hidden" scope="col">
                    IdMateria
                </th>
                <th class="text-center" scope="col">
                    Nombre
                </th>
            </tr>
            @foreach (ML.AlumnoMateria alumnomateria in Model.AlumnosMaterias)
            {
                <tr>
                    <td class="text-center hidden">
                        @alumnomateria.IdAlumnoMateria
                    </td>
                    <td class="text-center hidden">
                        @alumnomateria.IdAlumnoMateria
                    </td>
                    <td class="text-center">
                        <input type="checkbox" value="@alumnomateria.Materia.IdMateria" name="AlumnosMaterias">
                    </td>

                    <td class="text-left">
                        @alumnomateria.Materia.Nombre
                    </td>
                </tr>

            }
           

        </table>
        <div class="form-group col-md-12">
            <div class="text-right">
        
                <input class="btn btn-success" type="submit" value="Actualizar" />
                <a class="btn btn-danger" href="@Url.Action("GetMateriaAsignada", "AlumnoMateria", new { IdAlumno = Model.Alumno.IdAlumno })"> Regresar</a>
            </div>
        </div>
    </div>
</div>

PL/Views/AlumnoMateria/GetMateriaSinAsignar.cshtml
@model ML.AlumnoMateria
@{
    ViewBag.Title = "GetMateriaSinAsignar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">

        <h2>Materias Asiganadas Sin a: @Model.Alumno.Nombre  @Model.Alumno.ApellidoPaterno @Model.Alumno.ApellidoMaterno </h2>
    </div>
</div>

    <div class="row">
        @using (Html.BeginForm("GetMateriaSinAsignar", "AlumnoMateria", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-group hidden">
                @Html.LabelFor(model => model.Alumno.IdAlumno, new { @class = "control-label col-md-2 hidden" })
                <div class="col-md-3">
                    @Html.TextBoxFor(model => model.Alumno.IdAlumno, new { @class = "form-control hidden", @readonly = true })
                    @Html.ValidationMessageFor(model => model.Alumno.IdAlumno)
                </div>
            </div>
            
            
           
            <div class="row" style="padding-top:30px">
                <div class="col-md-12">
                    <table class="table table-bordered">
                        <tr>
                            <th class="text-center">
                                Selecciona
                            </th>
                            <th class="text-center " scope="col">
                                Nombre
                            </th>
                            <th class="text-left" scope="col">
                                Costo
                            </th>
                        </tr>
                        @foreach (ML.AlumnoMateria alumnomateria in Model.AlumnosMaterias)
                        {
                            <tr>
                                <td class="text-center hidden">
                                    @alumnomateria.Materia.IdMateria
                                </td>
                                <td class="text-center">
                                    <input id="checkbox_@alumnomateria.Materia.IdMateria" type="checkbox" value="@alumnomateria.Materia.IdMateria" name="AlumnosMaterias" onclick="CalcularTotal(@alumnomateria.Materia.Costo, @alumnomateria.Materia.IdMateria)">
                                </td>
                                <td class="text-left">
                                    @alumnomateria.Materia.Nombre
                                </td>
                                <td class="text-left">
                                    @alumnomateria.Materia.Costo
                                </td>
                            </tr>
                        }
                        <tr>
                            <td class="text-center">Total:</td>
                            <td></td>
                            <td id="total" class="text-center">0</td>
                        </tr>
                    </table>
                    <div class="form-group col-md-12">
                        <div class="text-right">
                            <input class="btn btn-success" type="submit" value="Actualizar" />
                            <a class="btn btn-danger" href="@Url.Action("GetMateriaAsignada", "AlumnoMateria", new { IdAlumno = Model.Alumno.IdAlumno })"> Regresar</a>
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>


    <script type="text/javascript">

        function CalcularTotal(Costo, IdMateria) {
            if ($('#checkbox_' + IdMateria).is(':checked')) {
                var total = parseInt($('#total').text())
                total = total + Costo;
                $('#total').text(total)
            }
            else {
                var total = parseInt($('#total').text())
                total = total - Costo;
                $('#total').text(total)
            }

        }
    </script>

PL/Views/AlumnoMateria/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "AlumnoMateria", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>