PL/Controllers/MateriaController.cs
using System;
using System.Web.Mvc;
using System.Net.Http;
using System.Collections.Generic;
using BL;

namespace PL.Controllers
{
    public class MateriaController : Controller
    {
        // GET: Materia
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Materia aseguradora = new ML.Materia();
            ML.Result resultAseguradoras = new ML.Result();
            resultAseguradoras.Objects = new List<object>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:61306/api/");

                var responseTask = client.GetAsync("Materia/GetAll");
                responseTask.Wait(); //esperar a que se resuelva la llamada al servicio

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        ML.Materia resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Materia>(resultItem.ToString());
                        resultAseguradoras.Objects.Add(resultItemList);
                    }
                }
                aseguradora.Materias = resultAseguradoras.Objects;
            }
            return View(aseguradora);
        }
       
        [HttpGet]
        public ActionResult Form(int? idMateria)
        {
            //ML.Result result = new ML.Result();
            ML.Materia materia = new ML.Materia();


            if (idMateria == null)
            {

                return View(materia);
            }

            else
            {

                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:61306/api/");

                    var responseTask = client.GetAsync("Materia/GetById/" + idMateria);
                    responseTask.Wait();
                    var resultAPI = responseTask.Result;
                    if (resultAPI.IsSuccessStatusCode)
                    {
                        var readTask = resultAPI.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();
                        ML.Materia resultItemList = new ML.Materia();
                        resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Materia>(readTask.Result.Object.ToString());
                        materia = resultItemList;


                    }

                }
                return View(materia);
                if (materia != null)
                {
                    return View();

                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al hacer la consulta del alumno ";
                    return View("Modal");
                }


                //hola

                //ML.Result result = BL.Aseguradora.GetById(idAseguradora.Value);
                //aseguradora.Usuario = new ML.Usuario();
                //aseguradora.Usuario.Usuarios = resultUsuario.Objects;
                //ML.Result result11 = BL.Aseguradora.GetById(idAseguradora.Value);



                //if (result.Correct)
                //{


                //    ML.Aseguradora ase = (ML.Aseguradora)result.Object;
                //    ase.Usuario.Usuarios = resultUsuario.Objects;
                //    return View(ase);

                //}
                //else
                //{
                //    ViewBag.Message = "Ocurrio un error al hacer la consulta de la aseguradora " + result.ErrorMessage;
                //    return View("Modal");
                //}


            }

        }
       
        [HttpPost]
        public ActionResult Form(ML.Materia aseguradora)
        {

            ML.Result result = new ML.Result();
            if (aseguradora.IdMateria == 0)
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:61306/api/");

                    //HTTP POST
                    var postTask = client.PostAsJsonAsync<ML.Materia>("Materia/Add", aseguradora);
                    postTask.Wait();

                    var resulAseguradora = postTask.Result;

                    if (resulAseguradora.IsSuccessStatusCode)
                    {
                        ViewBag.Mensaje = "Se ha insertado la aseguradora";
                        return PartialView("Modal");
                    }
                    else
                    {
                        ViewBag.Mensaje = "No ha insertado la aseguradora";
                        return PartialView("Modal");
                    }
                }
                return View("GetAll");
                //result = BL.Aseguradora.Add(aseguradora);
                //if (result.Correct)
                //{
                //    ViewBag.Mensaje = "Se ha insertado la aseguradora";
                //}
                //else
                //{
                //    ViewBag.Mensaje = "Ne ha insertado la aseguradora" + result.ErrorMessage;
                //}
            }
            else
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:61306/api/");

                    //HTTP POST
                    var postTask = client.PutAsJsonAsync<ML.Materia>("Materia/Update/" + aseguradora.IdMateria, aseguradora);
                    postTask.Wait();

                    var resultAlumno = postTask.Result;
                    if (resultAlumno.IsSuccessStatusCode)
                    {
                        ViewBag.Mensaje = "Se ha actualizado el Aseguradora";
                        return PartialView("Modal");
                    }
                }
                return PartialView("Modal");
            }

            return View();
        }
        [HttpPost]//servicio web
        public ActionResult Delete(ML.Materia materia)
        {
            ML.Result resultMaterias = new ML.Result();
            int IdAseguradora = materia.IdMateria;
            //int id = Aseguradora.IdAseguradora;
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:61306/api");

                //HTTP POST
                var postTask = client.GetAsync("Materia/Delete/" + IdAseguradora);
                postTask.Wait();

                var resultDelete = postTask.Result;
                if (resultDelete.IsSuccessStatusCode)
                {
                    ViewBag.Message = "Se Borro correctamente el Aseguradora";

                    //ML.Aseguradora Aseguradora = new ML.Producto();

                    //resultListAseguradora= BL.Aseguradora.GetAll(Aseguradora);
                    //return RedirectToAction("Modal");
                    return PartialView("Modal");
                }
                else
                {
                    ViewBag.Message = "Nose Se Borro correctamente el Aseguradora";

                }
            }

            //ML.Aseguradora Aseguradora = new ML.Aseguradora();

            //resultListAseguradora = BL.Aseguradora.GetAll(Aseguradora);
            //ViewBag.Message = "Nose Se Borro correctamente el Aseguradora";

            return View("Modal");
        }
       
    }
}

PL/Views/Materia/Form.cshtml
@model ML.Materia
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1 class="text-center">Formulario de Materia</h1>
<p>
    En este modulo puedes Agregar en el formulario de Materia<br />
</p>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Alumno</h2>
        </div>
    </div>
    @using (Html.BeginForm("Form", "Materia", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.IdMateria, new { @class = "visually-hidden" })

                    @Html.TextBoxFor(model => model.IdMateria, new { @class = "visually-hidden form-control" })
                    @Html.ValidationMessageFor(model => model.IdMateria)
                </div>
            </div>
            <div class="row">

                <div class="col-md-4">
                    @Html.LabelFor(model => model.Nombre)
                    <div class="input-group">
                        <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-user-plus fa-fade" style="color:#b257a2"></i></span>
                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre", @onkeypress = "SoloLetras(event, 'lblNombre', 'txtNombre')" })
                        @Html.ValidationMessageFor(model => model.Nombre)

                    </div>
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Costo)
                    <div class="input-group">
                        <span class="input-group-text" id="basic-addon1"><i class="bi bi-calendar2-minus-fill " style="color:#2c4ee7"></i></span>
                        @Html.TextBoxFor(model => model.Costo, new { @class = "form-control", @id = "txtFechaCreacion", @onkeypress = "SoloLetras(event, 'lblApellidoPaterno', 'txtApellidoPaterno')" })
                        @Html.ValidationMessageFor(model => model.Costo)

                    </div>
                </div>
               



            </div>


            <div class="form-group">
                <div class="col-md-3">
                    <input type="submit" value="Guardar" class="btn btn-success" />
                    @Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    }


</div>

PL/Views/Materia/GetAll.cshtml
@model ML.Materia
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <section>

        <h1 class="text-center">Lista de Materias</h1>
        <p>
            En este modulo puedes visualizar a las materias existentes, agregar, modificar y eliminar una materia
        </p>
    </section>

    <section>

        <div style="float:right;">
            <div class="row">
                @Html.ActionLink("Agregar", "Form", "Materia", htmlAttributes: new { @class = "btn btn-success bi bi-person-plus-fill" })
            </div>
        </div>

        <hr />
        <section>
            @if (Model.Materias == null)
            {
                <div class="row">
                    <div class="alert alert-danger" role="alert">
                        @ViewBag.Message
                    </div>
                </div>
            }
            else
            {
                <table class="table table-hover table-bordered table-responsive">
                    <thead>
                        <tr>
                            <td class="text-center" style=" font-weight:bold;">Editar</td>
                            <td class="visually-hidden">IdMateria</td>
                            <td class="text-center" style="font-weight:bold;">Nombre</td>
                            <td class="text-center" style="font-weight:bold;">Costo</td>
                            <td class="text-center" style=" font-weight:bold;">Eliminar</td>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (ML.Materia materia in Model.Materias)
                        {
                            <tr>
                                <td class="text-center"><a class="btn btn-warning bi bi-pencil-square" href="@Url.Action("Form", "Materia", new { IdMateria = materia.IdMateria })"></a></td>
                                <td class="visually-hidden">@materia.IdMateria</td>
                                <td>@materia.Nombre</td>
                                <td>@materia.Costo</td>
                                <td class="text-center"><a class="btn btn-danger bi bi-trash" href="@Url.Action("Delete", "Materia", new { IdMateria = materia.IdMateria})" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                            </tr>
                        }
                    </tbody>
                </table>

            }


        </section>
</div>

PL/Views/Materia/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>